// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AnchorLeft: typeof import('./src/components/AnchorLeft.vue')['default'];
        AnchorRight: typeof import('./src/components/AnchorRight.vue')['default'];
        BlogCard: typeof import('./src/components/BlogCard.vue')['default'];
        Blogs: typeof import('./src/components/Blogs.vue')['default'];
        ElAffix: typeof import('element-plus/es')['ElAffix'];
        ElAvatar: typeof import('element-plus/es')['ElAvatar'];
        ElBacktop: typeof import('element-plus/es')['ElBacktop'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElDivider: typeof import('element-plus/es')['ElDivider'];
        ElDrawer: typeof import('element-plus/es')['ElDrawer'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElPagination: typeof import('element-plus/es')['ElPagination'];
        ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
        Footer: typeof import('./src/components/Footer.vue')['default'];
        HeaderRebuild: typeof import('./src/components/HeaderRebuild.vue')['default'];
        HeaderRebuildPhone: typeof import('./src/components/HeaderRebuildPhone.vue')['default'];
        MainImg: typeof import('./src/components/MainImg.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
